### ISSUE TITLE
Add set_token method and don't do logon

### ISSUE THREAD

**Issue by lordspace** [there4/fogbugz-php-api#9]
Hi,

Nice & well organized code.
I wasn't feeling ok saving my user/email + pwd in the files.
So I created the following method and supply it with the token that I generated from the FogBugz control panel.

```
	public function set_token($token) {
		$this->token = (string) $token;
	}
```

**Comment by craig-davis** [comment]
If you'd like to make a pull request, I'll certainly pull this in. Thanks, and I'm glad to hear it's been useful.

**Comment by lordspace** [comment]
Yep. I was thinking about that. Will do it

**Comment by lordspace** [comment]
done
